user www-data ; 
worker_processes auto ;
pid /var/run/nginx.pid ;
daemon off;

events {
    worker_connections 1024 ;
}
http {
    access_log /var/log/nginx/access.log; // error logs
    gzip on; \\ enable gzip
    include /etc/nginx/mime.types;
    server {
        root /var/www/html ;
        listen 443 ssl  ; // listen on the port 443 with TLS/SSL encryption
        server_name localhost; // server name
        index index.php index.html index.htm; // Defines the default files served when a directory is requested.
        ssl_certificate /etc/nginx/certif.crt;
        ssl_certificate_key /etc/nginx/domain.key;
        ssl_protocols TLSv1.2;
        location ~ \.php$ {
            fastcgi_pass wordpress_v42:9000 ;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params ;
        }
    }                                                                                                                                                 
}